# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CH2jfNVWZ.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PyQt6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PyQt6.QtWidgets import (QApplication, QCheckBox, QLabel, QPlainTextEdit,
    QPushButton, QSizePolicy, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1106, 1011)
        self.Sputtering_label = QLabel(Form)
        self.Sputtering_label.setObjectName(u"Sputtering_label")
        self.Sputtering_label.setGeometry(QRect(40, 0, 151, 51))
        font = QFont()
        font.setPointSize(24)
        self.Sputtering_label.setFont(font)
        self.Sputtering_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.Base_pressure_label = QLabel(Form)
        self.Base_pressure_label.setObjectName(u"Base_pressure_label")
        self.Base_pressure_label.setGeometry(QRect(20, 60, 101, 21))
        self.Base_pressure_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.Flow_label = QLabel(Form)
        self.Flow_label.setObjectName(u"Flow_label")
        self.Flow_label.setGeometry(QRect(20, 310, 81, 21))
        self.Flow_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.Working_pressure_label = QLabel(Form)
        self.Working_pressure_label.setObjectName(u"Working_pressure_label")
        self.Working_pressure_label.setGeometry(QRect(20, 360, 181, 21))
        self.Working_pressure_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.Shutter_delay_label = QLabel(Form)
        self.Shutter_delay_label.setObjectName(u"Shutter_delay_label")
        self.Shutter_delay_label.setGeometry(QRect(20, 680, 131, 21))
        self.Shutter_delay_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.Process_time_label = QLabel(Form)
        self.Process_time_label.setObjectName(u"Process_time_label")
        self.Process_time_label.setGeometry(QRect(20, 730, 131, 21))
        self.Process_time_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.Power_label = QLabel(Form)
        self.Power_label.setObjectName(u"Power_label")
        self.Power_label.setGeometry(QRect(20, 840, 51, 21))
        self.Power_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.Voltage_label = QLabel(Form)
        self.Voltage_label.setObjectName(u"Voltage_label")
        self.Voltage_label.setGeometry(QRect(90, 840, 61, 21))
        self.Voltage_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.Current_label = QLabel(Form)
        self.Current_label.setObjectName(u"Current_label")
        self.Current_label.setGeometry(QRect(160, 840, 51, 21))
        self.Current_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.For_p_label = QLabel(Form)
        self.For_p_label.setObjectName(u"For_p_label")
        self.For_p_label.setGeometry(QRect(20, 780, 41, 21))
        self.For_p_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.Ref_p_label = QLabel(Form)
        self.Ref_p_label.setObjectName(u"Ref_p_label")
        self.Ref_p_label.setGeometry(QRect(130, 780, 41, 21))
        self.Ref_p_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.Process_list_label = QLabel(Form)
        self.Process_list_label.setObjectName(u"Process_list_label")
        self.Process_list_label.setGeometry(QRect(20, 903, 81, 21))
        self.Process_list_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.Base_pressure_edit = QPlainTextEdit(Form)
        self.Base_pressure_edit.setObjectName(u"Base_pressure_edit")
        self.Base_pressure_edit.setGeometry(QRect(20, 80, 201, 31))
        self.G1_checkbox = QCheckBox(Form)
        self.G1_checkbox.setObjectName(u"G1_checkbox")
        self.G1_checkbox.setGeometry(QRect(30, 210, 41, 24))
        self.G2_checkbox = QCheckBox(Form)
        self.G2_checkbox.setObjectName(u"G2_checkbox")
        self.G2_checkbox.setGeometry(QRect(100, 210, 41, 24))
        self.G3_checkbox = QCheckBox(Form)
        self.G3_checkbox.setObjectName(u"G3_checkbox")
        self.G3_checkbox.setGeometry(QRect(170, 210, 41, 24))
        self.Ar_checkbox = QCheckBox(Form)
        self.Ar_checkbox.setObjectName(u"Ar_checkbox")
        self.Ar_checkbox.setGeometry(QRect(30, 290, 41, 24))
        self.O2_checkbox = QCheckBox(Form)
        self.O2_checkbox.setObjectName(u"O2_checkbox")
        self.O2_checkbox.setGeometry(QRect(100, 290, 41, 24))
        self.N2_checkbox = QCheckBox(Form)
        self.N2_checkbox.setObjectName(u"N2_checkbox")
        self.N2_checkbox.setGeometry(QRect(170, 290, 41, 24))
        self.Ar_flow_edit = QPlainTextEdit(Form)
        self.Ar_flow_edit.setObjectName(u"Ar_flow_edit")
        self.Ar_flow_edit.setGeometry(QRect(20, 330, 61, 31))
        self.O2_flow_edit = QPlainTextEdit(Form)
        self.O2_flow_edit.setObjectName(u"O2_flow_edit")
        self.O2_flow_edit.setGeometry(QRect(90, 330, 61, 31))
        self.N2_flow_edit = QPlainTextEdit(Form)
        self.N2_flow_edit.setObjectName(u"N2_flow_edit")
        self.N2_flow_edit.setGeometry(QRect(160, 330, 61, 31))
        self.Working_pressure_edit = QPlainTextEdit(Form)
        self.Working_pressure_edit.setObjectName(u"Working_pressure_edit")
        self.Working_pressure_edit.setGeometry(QRect(20, 380, 201, 31))
        self.RF_power_edit = QPlainTextEdit(Form)
        self.RF_power_edit.setObjectName(u"RF_power_edit")
        self.RF_power_edit.setGeometry(QRect(20, 600, 201, 31))
        self.DC_power_edit = QPlainTextEdit(Form)
        self.DC_power_edit.setObjectName(u"DC_power_edit")
        self.DC_power_edit.setGeometry(QRect(20, 650, 201, 31))
        self.Shutter_delay_edit = QPlainTextEdit(Form)
        self.Shutter_delay_edit.setObjectName(u"Shutter_delay_edit")
        self.Shutter_delay_edit.setGeometry(QRect(20, 700, 201, 31))
        self.Process_time_edit = QPlainTextEdit(Form)
        self.Process_time_edit.setObjectName(u"Process_time_edit")
        self.Process_time_edit.setGeometry(QRect(20, 750, 201, 31))
        self.Process_list_button = QPushButton(Form)
        self.Process_list_button.setObjectName(u"Process_list_button")
        self.Process_list_button.setGeometry(QRect(110, 900, 111, 31))
        self.Power_edit = QPlainTextEdit(Form)
        self.Power_edit.setObjectName(u"Power_edit")
        self.Power_edit.setGeometry(QRect(20, 860, 61, 31))
        self.Current_edit = QPlainTextEdit(Form)
        self.Current_edit.setObjectName(u"Current_edit")
        self.Current_edit.setGeometry(QRect(160, 860, 61, 31))
        self.Voltage_edit = QPlainTextEdit(Form)
        self.Voltage_edit.setObjectName(u"Voltage_edit")
        self.Voltage_edit.setGeometry(QRect(90, 860, 61, 31))
        self.For_p_edit = QPlainTextEdit(Form)
        self.For_p_edit.setObjectName(u"For_p_edit")
        self.For_p_edit.setGeometry(QRect(20, 800, 91, 31))
        self.Ref_p_edit = QPlainTextEdit(Form)
        self.Ref_p_edit.setObjectName(u"Ref_p_edit")
        self.Ref_p_edit.setGeometry(QRect(130, 800, 91, 31))
        self.Start_button = QPushButton(Form)
        self.Start_button.setObjectName(u"Start_button")
        self.Start_button.setGeometry(QRect(20, 940, 91, 61))
        self.Stop_button = QPushButton(Form)
        self.Stop_button.setObjectName(u"Stop_button")
        self.Stop_button.setGeometry(QRect(130, 940, 91, 61))
        self.RGA_Graph = QWidget(Form)
        self.RGA_Graph.setObjectName(u"RGA_Graph")
        self.RGA_Graph.setGeometry(QRect(240, 70, 841, 311))
        self.OES_Graph = QWidget(Form)
        self.OES_Graph.setObjectName(u"OES_Graph")
        self.OES_Graph.setGeometry(QRect(240, 400, 841, 351))
        self.OES_graph_label = QLabel(Form)
        self.OES_graph_label.setObjectName(u"OES_graph_label")
        self.OES_graph_label.setGeometry(QRect(240, 380, 131, 21))
        self.OES_graph_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.RGA_graph_label = QLabel(Form)
        self.RGA_graph_label.setObjectName(u"RGA_graph_label")
        self.RGA_graph_label.setGeometry(QRect(240, 50, 131, 21))
        self.RGA_graph_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.Main_shutter_checkbox = QCheckBox(Form)
        self.Main_shutter_checkbox.setObjectName(u"Main_shutter_checkbox")
        self.Main_shutter_checkbox.setGeometry(QRect(30, 170, 161, 24))
        self.log_message = QPlainTextEdit(Form)
        self.log_message.setObjectName(u"log_message")
        self.log_message.setGeometry(QRect(240, 840, 841, 161))
        self.Intergration_time_edit = QPlainTextEdit(Form)
        self.Intergration_time_edit.setObjectName(u"Intergration_time_edit")
        self.Intergration_time_edit.setGeometry(QRect(20, 130, 201, 31))
        self.Integration_time_label = QLabel(Form)
        self.Integration_time_label.setObjectName(u"Integration_time_label")
        self.Integration_time_label.setGeometry(QRect(20, 110, 121, 21))
        self.Integration_time_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.DC_power_checkbox = QCheckBox(Form)
        self.DC_power_checkbox.setObjectName(u"DC_power_checkbox")
        self.DC_power_checkbox.setGeometry(QRect(20, 630, 121, 24))
        self.RF_power_checkbox = QCheckBox(Form)
        self.RF_power_checkbox.setObjectName(u"RF_power_checkbox")
        self.RF_power_checkbox.setGeometry(QRect(20, 580, 121, 24))
        self.process_state = QPlainTextEdit(Form)
        self.process_state.setObjectName(u"process_state")
        self.process_state.setGeometry(QRect(290, 10, 791, 51))
        self.process_state.setFont(font)
        self.G2_target_name = QPlainTextEdit(Form)
        self.G2_target_name.setObjectName(u"G2_target_name")
        self.G2_target_name.setGeometry(QRect(90, 250, 61, 31))
        self.G1_target_name = QPlainTextEdit(Form)
        self.G1_target_name.setObjectName(u"G1_target_name")
        self.G1_target_name.setGeometry(QRect(20, 250, 61, 31))
        self.G3_target_name = QPlainTextEdit(Form)
        self.G3_target_name.setObjectName(u"G3_target_name")
        self.G3_target_name.setGeometry(QRect(160, 250, 61, 31))
        self.Flow_label_2 = QLabel(Form)
        self.Flow_label_2.setObjectName(u"Flow_label_2")
        self.Flow_label_2.setGeometry(QRect(20, 230, 91, 21))
        self.Flow_label_2.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.note_edit = QPlainTextEdit(Form)
        self.note_edit.setObjectName(u"note_edit")
        self.note_edit.setGeometry(QRect(240, 760, 841, 71))
        self.RF_pulse_checkbox = QCheckBox(Form)
        self.RF_pulse_checkbox.setObjectName(u"RF_pulse_checkbox")
        self.RF_pulse_checkbox.setGeometry(QRect(20, 420, 161, 24))
        self.RF_pulse_edit = QPlainTextEdit(Form)
        self.RF_pulse_edit.setObjectName(u"RF_pulse_edit")
        self.RF_pulse_edit.setGeometry(QRect(20, 440, 201, 31))
        self.Rf_pulse_freq_label = QLabel(Form)
        self.Rf_pulse_freq_label.setObjectName(u"Rf_pulse_freq_label")
        self.Rf_pulse_freq_label.setGeometry(QRect(20, 470, 181, 21))
        self.Rf_pulse_freq_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.Rf_pulse_duty_cycle_label = QLabel(Form)
        self.Rf_pulse_duty_cycle_label.setObjectName(u"Rf_pulse_duty_cycle_label")
        self.Rf_pulse_duty_cycle_label.setGeometry(QRect(20, 520, 181, 21))
        self.Rf_pulse_duty_cycle_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.Rf_pulse_freq_edit = QPlainTextEdit(Form)
        self.Rf_pulse_freq_edit.setObjectName(u"Rf_pulse_freq_edit")
        self.Rf_pulse_freq_edit.setGeometry(QRect(20, 490, 201, 31))
        self.Rf_pulse_duty_cycle_edit = QPlainTextEdit(Form)
        self.Rf_pulse_duty_cycle_edit.setObjectName(u"Rf_pulse_duty_cycle_edit")
        self.Rf_pulse_duty_cycle_edit.setGeometry(QRect(20, 540, 201, 31))

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.Sputtering_label.setText(QCoreApplication.translate("Form", u"Sputtering", None))
        self.Base_pressure_label.setText(QCoreApplication.translate("Form", u"Base pressure", None))
        self.Flow_label.setText(QCoreApplication.translate("Form", u"Flow [sccm]", None))
        self.Working_pressure_label.setText(QCoreApplication.translate("Form", u"Working pressure [mTorr]", None))
        self.Shutter_delay_label.setText(QCoreApplication.translate("Form", u"Shutter delay [min]", None))
        self.Process_time_label.setText(QCoreApplication.translate("Form", u"Process time [min]", None))
        self.Power_label.setText(QCoreApplication.translate("Form", u"Power", None))
        self.Voltage_label.setText(QCoreApplication.translate("Form", u"Voltage", None))
        self.Current_label.setText(QCoreApplication.translate("Form", u"Current", None))
        self.For_p_label.setText(QCoreApplication.translate("Form", u"For.p", None))
        self.Ref_p_label.setText(QCoreApplication.translate("Form", u"Ref.p", None))
        self.Process_list_label.setText(QCoreApplication.translate("Form", u"Process list", None))
        self.G1_checkbox.setText(QCoreApplication.translate("Form", u"G1", None))
        self.G2_checkbox.setText(QCoreApplication.translate("Form", u"G2", None))
        self.G3_checkbox.setText(QCoreApplication.translate("Form", u"G3", None))
        self.Ar_checkbox.setText(QCoreApplication.translate("Form", u"Ar", None))
        self.O2_checkbox.setText(QCoreApplication.translate("Form", u"O2", None))
        self.N2_checkbox.setText(QCoreApplication.translate("Form", u"N2", None))
        self.Process_list_button.setText(QCoreApplication.translate("Form", u"file path", None))
        self.Start_button.setText(QCoreApplication.translate("Form", u"START", None))
        self.Stop_button.setText(QCoreApplication.translate("Form", u"STOP", None))
        self.OES_graph_label.setText(QCoreApplication.translate("Form", u"OES data", None))
        self.RGA_graph_label.setText(QCoreApplication.translate("Form", u"RGA", None))
        self.Main_shutter_checkbox.setText(QCoreApplication.translate("Form", u"Main Shutter Open", None))
        self.Integration_time_label.setText(QCoreApplication.translate("Form", u"Integration time", None))
        self.DC_power_checkbox.setText(QCoreApplication.translate("Form", u"DC power [W]", None))
        self.RF_power_checkbox.setText(QCoreApplication.translate("Form", u"RF power [W]", None))
        self.process_state.setPlainText("")
        self.Flow_label_2.setText(QCoreApplication.translate("Form", u"Target name", None))
        self.RF_pulse_checkbox.setText(QCoreApplication.translate("Form", u"RF Pulse power [W]", None))
        self.Rf_pulse_freq_label.setText(QCoreApplication.translate("Form", u"RF Pulse Freq", None))
        self.Rf_pulse_duty_cycle_label.setText(QCoreApplication.translate("Form", u"RF Pulse Duty Cycle", None))
    # retranslateUi

